version: '3.1'
services:
  mongo:
    container_name: mongo
    #构建容器
    build: ./dump
    ports:
        - "27017:27017"
    # 添加数据圈 数据库的数据文件映射到本地 data/db
    volumes: 
        - ./data/db:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    # ports:
    #   - 8081:8081
  server:
    container_name: server
    depends_on:
      - mongo
    #构建容器
    build: ./server
    ports:
        - "7001:7001"
  front:
    container_name: front
    depends_on:
      - server
    #构建容器
    build: ./front
    ports:
        - "8888:3000"