version: '3.1'
services:
  # mongo:
  #   container_name: mongo
  #   #构建容器
  #   build: ./dump
  #   ports:
  #       - "27017:27017"
  #   # 添加数据卷 数据库的数据文件映射到本地 data/db
  #   volumes: 
  #       - ./data/db:/data/db
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo
  #   # ports:
  #   #   - 8081:8081
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  server:
    container_name: server
    depends_on:
      - mysql
    #构建容器
    build: ../server_simle
    ports:
        - "7001:7001"
  front:
    container_name: front
    depends_on:
      - server
    #构建容器
    build: ../core
    ports:
        - "8888:3000"